version: "3"
services:
  db:
    image: mysql:latest
    container_name: invoice_management_system
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=invoice_management_system_db
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
